# Generated by Django 6.1.1 on 2026-09-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('complete', 'Complete'), ('expired', 'Expired')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
