# Generated by Django 6.1.1 on 2026-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_subtask_status_subtask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in_progress'), ('Complete', 'complete'), ('Expired', 'expired')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in_progress'), ('Complete', 'complete'), ('Expired', 'expired')], default='In Progress', max_length=20),
        ),
    ]
