# Generated by Django 6.1.1 on 2026-09-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_category_options_alter_priority_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todos.task'),
        ),
    ]
