# Generated by Django 6.1.1 on 2026-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_subtask_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in_progress'), ('Complete', 'complete')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in_progress'), ('Complete', 'complete')], default='In Progress', max_length=20),
        ),
    ]
