# Generated by Django 6.1.1 on 2026-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in_progress'), ('Completed', 'completed')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in_progress'), ('Completed', 'completed')], default='In Progress', max_length=20),
        ),
    ]
