# Generated by Django 6.1.1 on 2026-10-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todos.task'),
        ),
    ]
